version: '3.4'

services:
  mgazadanie:
    image: mgazadanie
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    # volumes:
      # - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

# volumes: postgres_data {}
